### ISSUE TITLE
naming convention and use of node-red keyword

### ISSUE THREAD

**Issue by ukmoose** [thunderace/node-red-node-newtifrypro#1]
Thanks for creating a new node for node-red

Have you read the page on packaging in the documentation?
http://nodered.org/docs/creating-nodes/packaging

The page asks that you don't include node-red as a keyword until the node is ready to be used, (which given the request not to install in the readme I assume it isn't).

It also defines the naming convention to make it clear that the node isn't maintained by the node-red project.   It would be great if you could update you project to follow these.

**Comment by thunderace** [comment]
Hello, it's not a new node, just an update.
So, i will modifiy the node name according to the naming convention.
And the '(Not yet : work in progress)'is an error. thank you.

**Comment by thunderace** [comment]
done
